Repository NicholasNagy/Parent_Teacher_Web_App, pull requests merged in 2018-10, with the labels that each got.

#57 Created a Parent Profile Page template: Issue #47 #48
  app.js
  headers/headerProfile.ejs
  routes/editParentProfileInfo.js
  routes/login.js
  routes/parentProfile.js
  routes/parenthomepage.js
  routes/teacherProfile.js
  stylesheets/res/placeholderProfilePicture.png
  stylesheets/style.css
  stylesheets/styles_home.css
  stylesheets/styles_profile.css
  views/comments.ejs
  views/headers/headerProfile.ejs
  views/homepage.ejs
  views/index.ejs
  views/parenthomepage.ejs
  views/profile.ejs
Labels: High Priority

#63 Conflict resolve plus minor fixes
  .DS_Store
  .idea/workspace.xml
  app.js
  public/.DS_Store
  routes/.DS_Store
  routes/Messengerindex.js
  routes/comments.js
  routes/index.js
  routes/login.js
  routes/logout.js
  routes/messenger.js
  routes/parentProfile.js
  routes/posting.js
  routes/reply.js
  routes/toCommentPage.js
  views/comments.ejs
  views/homepage.ejs
  views/messenger.ejs
  views/parenthomepage.ejs
  views/profile.ejs
Labels: High Priority

#77 Started using promises
  functiontests/functiontesting.js
  routes/functions.js
  routes/posting.js
  routes/reply.js
Labels: Medium Priority

#79 wall feature
  functiontests/functiontesting.js
  functiontests/functiontestingcleanup.js
  routes/functions.js
  routes/index.js
  routes/login.js
  routes/posting.js
  routes/reply.js
  routes/toCommentPage.js
  views/parenthomepage.ejs
Labels: High Priority

#82 Added search and friends ISSUE #72
  app.js
  routes/addFriends.js
  routes/friends.js
  routes/login.js
  routes/searchFriends.js
  stylesheets/styles_friends.css
  views/friends.ejs
  views/headers/headerFriends.ejs
  views/homepage.ejs
  views/parenthomepage.ejs
Labels: High Priority, Medium Priority

#86 Adding new test 1
  .travis.yml
  functiontests/loginsignuptesting.js
  functiontests/signuplogintestingcleanup.js
Labels: High Priority

#84 Nicholas nagy testrefactoring
  .travis.yml
  functiontests/loginsignuptesting.js
  functiontests/signuplogintestingcleanup.js
  routes/functions.js
  routes/index.js
  routes/login.js
  routes/posting.js
  routes/signup.js
  views/parenthomepage.ejs
Labels: High Priority

#92 TeacherViewingProfile- Refactoring for Integration- issue #62
  app.js
  routes/_DS_Store
  routes/editParentProfileInfo.js
  routes/functions.js
  routes/viewProfile.js
  views/_DS_Store
  views/headers/_DS_Store
  views/parenthomepage.ejs
Labels: High Priority

#91 Added email duplicate testing
  .travis.yml
  functiontests/checkEmailDuplicates.js
  functiontests/profileEditTesting.js
  functiontests/profileViewTesting.js
Labels: High Priority

#96 post images functionality, issue #69
  app.js
  routes/functions.js
  routes/login.js
  routes/posting.js
  views/parenthomepage.ejs
Labels: High Priority

#97 added capability for view friend wall
  app.js
  routes/goToWall.js
  views/friends.ejs
Labels: High Priority

#94 Added like and dislike functionality
  app.js
  routes/dislike.js
  routes/functions.js
  routes/goToWall.js
  routes/like.js
  routes/login.js
  routes/posting.js
  routes/viewProfile.js
  views/friends.ejs
  views/parenthomepage.ejs
Labels: High Priority
