Repository NicholasNagy/Parent_Teacher_Web_App, pull requests merged in 2018-11, with the labels that each got.

#106 Refactored code a little bit and Improved Control Flow
  functiontests/profileEditTesting.js
  routes/addFriends.js
  routes/addToGroup.js
  routes/createGroups.js
  routes/dislike.js
  routes/editGroup.js
  routes/editParentProfileInfo.js
  routes/friends.js
  routes/functions.js
  routes/goToWall.js
  routes/groups.js
  routes/like.js
  routes/login.js
  routes/posting.js
  routes/render.js
  routes/reply.js
  routes/searchFriends.js
  routes/searchUsers.js
  routes/toCommentPage.js
  routes/viewProfile.js
  views/comments.ejs
  views/editGroup.ejs
  views/friends.ejs
  views/groups.ejs
  views/parenthomepage.ejs
  views/profile.ejs
Labels: High Priority

#113 messenger refactored
  .idea/workspace.xml
  node_modules/ejs/Jakefile
  node_modules/ejs/LICENSE
  node_modules/ejs/README.md
  node_modules/ejs/ejs.js
  node_modules/ejs/ejs.min.js
  node_modules/ejs/lib/ejs.js
  node_modules/ejs/lib/utils.js
  node_modules/ejs/package.json
  node_modules/isarray/.npmignore
  node_modules/isarray/.travis.yml
  node_modules/isarray/Makefile
  node_modules/isarray/component.json
  node_modules/isarray/test.js
  routes/Messengerindex.js
  routes/viewParents.js
  views/friends.ejs
  views/parenthomepage.ejs
  views/viewParent.ejs
Labels: High Priority

#116 Delete testscript
  app.js
  ptwebapptests/cleanup.js
  ptwebapptests/test1.js
  ptwebapptests/test1.py
  routes/comments.js
  routes/parentProfile.js
  routes/parenthomepage.js
  routes/teacherProfile.js
  routes/users.js
  routes/viewParents.js
  test.js
  testscript
  views/error.ejs
  views/homepage.ejs
  views/teachersignuptest.ejs
Labels: High Priority

#124 Messenger style update
  routes/Messengerindex.js
  views/messenger.ejs
Labels: High Priority

#129 View a friends groups and friends from their profile
  app.js
  routes/viewFriendProfile.js
  stylesheets/styles_friends.css
  stylesheets/styles_groups.css
  stylesheets/styles_home.css
  stylesheets/styles_profile.css
  views/friendProfile.ejs
  views/friends.ejs
  views/parenthomepage.ejs
  views/profile.ejs
Labels: Medium Priority, Sub Task

#133 forgot-password feature
  app.js
  routes/Messengerindex.js
  routes/forgotPassword.js
  routes/friends.js
  routes/index.js
  routes/signup.js
  routes/viewFriendProfile.js
  views/forgotPassword.ejs
  views/friendProfile.ejs
  views/friends.ejs
  views/index.ejs
  views/messenger.ejs
  views/parenthomepage.ejs
  views/profile.ejs
Labels: High Priority

#136 Allow groups’ admins to accept/reject new members to groups
  app.js
  routes/addToGroup.js
  routes/declineGroupRequest.js
  routes/editGroup.js
  routes/friends.js
  routes/groupRequest.js
  routes/searchUsers.js
  routes/viewFriendProfile.js
  stylesheets/styles_groups.css
  views/editGroup.ejs
  views/error.ejs
  views/friendProfile.ejs
  views/friends.ejs
  views/parenthomepage.ejs
  views/profile.ejs
Labels: High Priority

#139 Styling changes to forgot password and notifications dropdown menu
  stylesheets/style.css
  stylesheets/styles_home.css
  views/forgotPassword.ejs
  views/index.ejs
  views/parenthomepage.ejs
Labels: Low Priority

#141 Khaled badran test branch
  .travis.yml
  functiontests/ImagePostingTest.js
  functiontests/ImagePostingTestCleanUp.js
  functiontests/createGroupTest.js
  functiontests/createGroupTestCleanUp.js
  functiontests/searchTest.js
  public/uploads/test-Image.png
  public/uploads/test.txt
  routes/Messengerindex.js
  routes/createGroups.js
  routes/functions.js
  routes/searchUsers.js
  views/messenger.ejs
Labels: High Priority

#142 Check ID Duplicates in Users table test Added #138
  .travis.yml
  functiontests/checkIDDubplicates.js
Labels: Medium Priority

#149 Add tagging feature to posts
  routes/functions.js
  routes/posting.js
  routes/reply.js
  stylesheets/styles_home.css
  views/comments.ejs
  views/parenthomepage.ejs
Labels: High Priority

#157 #152 #153 Handling like/dislike incrementing without limits and forgot password error handling
  .idea/workspace.xml
  routes/dislike.js
  routes/forgotPassword.js
  routes/like.js
  views/forgotPassword.ejs
Labels: High Priority
